@extends('layouts.console')
@section('title', 'New referral')
@section('heading', 'New referral')
@section('content')
<div class="mx-auto max-w-5xl">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-4">
        <div><p class="section-eyebrow">Fast clinical handover</p><h2 class="page-heading mt-2 text-3xl">Send a referral</h2><p class="mt-2 max-w-2xl text-sm text-slate-500">Share the essentials first. Add detail only when it helps the receiving team act.</p></div>
        <span class="badge bg-red-50 text-red-700">Emergency-ready</span>
    </div>
    <form id="referral-form" class="space-y-5" enctype="multipart/form-data">
        <section class="card border-l-4 border-l-red-400 p-5 sm:p-6">
            <div class="flex items-start gap-3"><span class="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-red-50 text-red-600"><svg viewBox="0 0 20 20" fill="none" class="h-4 w-4"><path d="M10 4v6m0 3v.5M3 16h14L10 3 3 16Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg></span><div><h3 class="font-bold text-brand-950">Send the essentials</h3><p class="mt-1 text-sm leading-6 text-slate-500">The receiving hospital will be notified and a care-team owner assigned as soon as you send.</p></div></div>
            <div class="mt-5 grid gap-4 sm:grid-cols-2"><div><label class="label" for="hospital">Receiving hospital</label><select class="input mt-1" id="hospital" name="receiving_hospital_id" required><option value="">Choose hospital</option>@foreach($hospitals as $hospital)<option value="{{ $hospital->id }}">{{ $hospital->name }}</option>@endforeach</select></div><div><label class="label" for="department">Receiving department</label><input class="input mt-1" id="department" name="department" placeholder="Emergency, ICU, Cardiology" required></div></div>
        </section>
        <section class="card p-5 sm:p-6"><h3 class="font-bold text-brand-950">Patient</h3><div class="mt-4 grid gap-4 sm:grid-cols-[1.5fr_0.5fr]"><div><label class="label" for="patient-name">Patient name</label><input class="input mt-1" id="patient-name" name="patient[name]" placeholder="Full name" required></div><div><label class="label" for="patient-age">Age</label><input class="input mt-1" id="patient-age" name="patient[age]" type="number" min="0" max="130" placeholder="Years"></div></div></section>
        <section class="card p-5 sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-bold text-brand-950">Clinical picture</h3><p class="mt-1 text-sm text-slate-500">What does the receiving team need to know right now?</p></div><label class="flex items-center gap-2 text-sm font-semibold text-red-700"><input class="h-4 w-4 accent-red-600" id="is-emergency" name="is_emergency" type="checkbox" value="1"> Emergency transfer</label></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><div><label class="label" for="urgency">Urgency</label><select class="input mt-1" id="urgency" name="urgency"><option value="routine">Routine</option><option value="urgent">Urgent</option><option value="emergent">Emergent</option><option value="critical">Critical</option></select></div><div><label class="label" for="vitals-bp">Blood pressure <span class="font-normal text-slate-400">(optional)</span></label><input class="input mt-1" id="vitals-bp" name="vitals[bp]" placeholder="120/80"></div><div class="sm:col-span-2"><label class="label" for="referral-reason">Reason for referral</label><textarea class="input mt-1 min-h-24" id="referral-reason" name="referral_reason" placeholder="Diagnosis, concern, or reason for transfer" required></textarea></div><div class="sm:col-span-2"><label class="label" for="symptoms">Current symptoms <span class="font-normal text-slate-400">(optional)</span></label><textarea class="input mt-1 min-h-20" id="symptoms" name="symptoms" placeholder="What is happening now?"></textarea></div></div></section>
        <details class="card group"><summary class="flex cursor-pointer list-none items-center justify-between p-5 font-semibold text-brand-950"><span>Additional clinical details</span><span class="text-xl font-normal text-slate-400 transition group-open:rotate-45">+</span></summary><div class="grid gap-4 border-t border-slate-100 p-5 sm:grid-cols-2"><div><label class="label" for="vitals-hr">Heart rate</label><input class="input mt-1" id="vitals-hr" name="vitals[hr]" type="number"></div><div><label class="label" for="vitals-spo2">SpO₂</label><input class="input mt-1" id="vitals-spo2" name="vitals[spo2]" type="number" min="0" max="100"></div><div><label class="label" for="consciousness">Consciousness</label><input class="input mt-1" id="consciousness" name="consciousness" placeholder="Alert, drowsy..."></div><div><label class="label" for="blood-group">Blood group</label><input class="input mt-1" id="blood-group" name="patient[blood_group]"></div><div class="sm:col-span-2"><label class="label" for="existing-conditions">Existing conditions</label><textarea class="input mt-1 min-h-20" id="existing-conditions" name="existing_conditions"></textarea></div><div class="sm:col-span-2"><label class="label" for="current-interventions">Current interventions</label><textarea class="input mt-1 min-h-20" id="current-interventions" name="current_interventions"></textarea></div><div class="sm:col-span-2"><label class="label" for="attachments">Attachments</label><input class="input mt-1 py-2" id="attachments" name="attachments[]" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx,.csv,.txt"></div></div></details>
        <div id="referral-error" class="hidden rounded-[7px] border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"></div><div class="flex flex-wrap items-center justify-between gap-3"><a href="{{ route('referrals.index') }}" class="btn-ghost">Cancel</a><button id="referral-submit" type="submit" class="btn-accent px-6">Send referral</button></div>
    </form>
</div>
@endsection
